[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"] # import mocha
live_config_reload = true # live reload config

[window]
dynamic_padding = false
decorations_theme_variant = "Dark"

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true
