# Modified from catppuccin/alacritty
[colors]
indexed_colors = [{ index = 16, color = "#FAB387" }, { index = 17, color = "#F5E0DC" } ]
vi_mode_cursor = { text = "#1E1E2E", cursor = "#B4BEFE" } # base, lavender
footer_bar = { foreground = "#1E1E2E", background = "#A6ADC8" } # base, subtext0

[colors.primary]
background = "#1E1E2E" # base
foreground = "#CDD6F4" # text
# Bright and dim foreground colors
dim_foreground = "#CDD6F4" # text
bright_foreground = "#CDD6F4" # text

    # Cursor colors
[colors.cursor]
text = "#1E1E2E" # base
cursor = "#F5E0DC" # rosewater


    # Search colors
[colors.search]
matches = {foreground = "#1E1E2E", background = "#A6ADC8" } # base, subtext0
focused_match = { foreground = "#1E1E2E", background = "#A6E3A1" } # base, green

    # Keyboard regex hints
[colors.hints]
start = { foreground = "#1E1E2E", background = "#F9E2AF" } # base, yellow
end = { foreground = "#1E1E2E", background = "#A6ADC8" } # base, subtext0

    # Selection colors
[colors.selection]
text = "#1E1E2E" # base
background = "#F5E0DC" # rosewater

    # Normal colors
[colors.normal]
black = "#45475A" # surface1
red = "#F38BA8" # red
green = "#A6E3A1" # green
yellow = "#F9E2AF" # yellow
blue = "#89B4FA" # blue
magenta = "#F5C2E7" # pink
cyan = "#94E2D5" # teal
white = "#E6EFFD" # subtext1

    # Bright colors - shift up by 8 in each
[colors.bright]
black = "#585B70" # surface2
red = "#FB93B0" # red
green = "#AEECA9" # green
yellow = "#FFEAB7" # yellow
blue = "#91BCFF" # blue
magenta = "#FDCAEF" # pink
cyan = "#9CEADD" # teal
white = "#EDF7FF" # text

    # Dim colors - shift down by 8 in each
[colors.dim]
black = "#313244" # surface0
red = "#EA83A0" # red
green = "#9EDB99" # green
yellow = "#F1DAA7" # yellow
blue = "#81ABF2" # blue
magenta = "#EDBADF" # pink
cyan = "#8CDACD" # teal
white = "#DEE7F6" # subtext0

